# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Coverage

on:
    push:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3

            -   uses: actions/setup-node@v3
                with:
                    node-version: '14.x'
                    registry-url: 'https://registry.npmjs.org'

            - name: Build and install packages
              run: |
                  npm ci
                  npm run build
                  npm run test:coverage

            - name: Upload Code coverage report
              uses: codecov/codecov-action@v3.1.0
              with:
                  token: ${{ secrets.codecov }}
                  file: ./writable/coverage/*.json
